version: "3"

services:
  jumpaku-dinner-dev:
    build: "./"
    working_dir: "/project_root/"
    command: ["sleep", "infinity"]
    volumes:
      - "./../:/project_root/:delegated"
    ports:
      - "9000:9000"
      - "3000:3000"
  test-db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_database
  test-db-redis:
    image: "redis:6.2-rc3-buster"
  # docker-compose up postgres
  # docker-compose exec postgres psql --username='postgres_user' --dbname='postgres_database' --password
